// imageData.ts
export const imgArray: { title: string; src: string; selected: boolean; amount: string; offer: string; }[] = [
  { title: "CLOTH", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmVAfbFrsJ5DEbYbWMddFZcYUFBXiP9XMWyaUvxef8q5pB/cloth.jpg", selected: false, amount: "8", offer: "Burn 8 WOOL ERC20 + Holding Character NFT" },
  { title: "BRICK", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmVAfbFrsJ5DEbYbWMddFZcYUFBXiP9XMWyaUvxef8q5pB/brick.jpg", selected: false, amount: "2", offer: "Burn 2 CLAY ERC20 + Holding Character NFT" },
  { title: "ROPE", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmdKgHEsYGWLFA5tu47TPtChEbnTDFqqKE7PoncFz2imqe/rope.jpg", selected: false, amount: "3", offer: "Burn 3 WOOL ERC20 + Holding Character NFT" },
  { title: "LUMBER", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmVAfbFrsJ5DEbYbWMddFZcYUFBXiP9XMWyaUvxef8q5pB/lumber.jpg", selected: false, amount: "2", offer: "Burn 2 WOOD ERC20 + Holding SAW NFT + Holding Character NFT" },
  { title: "FORGE", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmaNnS2tTaP889iQewvmx3wsQ1fyZKwdLhBwxtaSzgVmPd", selected: false, amount: "100", offer: "Burn 100 BRICK ERC20 + Burn 3 CLAY + Holding a Character NFT" },
  { title: "HAMMER", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmXiaa2oEcPnjxRGzrGPcD72Cw5PbBTPL54npYU7UZAR8e", selected: false, amount: "1", offer: "Burn 1 WOOD ERC20 + Burn 1 IRON ERC20 + Holding FORGE + ANVIL + CHARACTER NFT" },
  { title: "ANVIL", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmdKgHEsYGWLFA5tu47TPtChEbnTDFqqKE7PoncFz2imqe/anvil.jpg", selected: false, amount: "100", offer: "Burn 100 IRON ERC20 + Burn 3 WOOD  + Holding FORGE NFT + Holding Character NFT" },
  { title: "NET", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmdKgHEsYGWLFA5tu47TPtChEbnTDFqqKE7PoncFz2imqe/net.jpg", selected: false, amount: "100", offer: "100 BRICK ERC20 Make 1 NAILS NFT" },
  { title: "AXE", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmdKgHEsYGWLFA5tu47TPtChEbnTDFqqKE7PoncFz2imqe/axe.jpg", selected: false, amount: "1", offer: " Burn 1 WOOD + 2 IRON + Holding FORGE + ANVIL + CHARACTER NFT" },
  { title: "SAW", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmVNkURhjGhN4pZY7Y5zdSddTKE3jTfnpPCdHq3qEaZ19T", selected: false, amount: "1", offer: "Burn 1 WOOD + 3 IRON + Holding FORGE + ANVIL + CHARACTER NFT" },
  { title: "PICKAXE", src: "https://ipfs.blocksscan.io/unsafe/https://gateway.pinata.cloud/ipfs/QmdKgHEsYGWLFA5tu47TPtChEbnTDFqqKE7PoncFz2imqe/pickaxe.jpg", selected: false, amount: "1", offer: "Burn 1 WOOD + 3 IRON + Holding FORGE + ANVIL + CHARACTER NFT"},
];
